apiVersion: v1
kind: Service
metadata:
  name: simple-website
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  labels:
    app: demo
spec:
  # automatically create an external load-balanced IP for the service.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: simple-website
